### ISSUE TITLE
"Can't set headers after they are sent" error when using 3.2.4 app with 3.3.0 API

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-api#101]
Hello team,

When using our app compatible for Wazuh 3.2.4 with a 3.3.0 version of the Wazuh API, we get the following error trace:
```
WazuhAPI 2018-06-10 21:32:08: [::ffff:127.0.0.1] GET /agents?offset=0&limit=1 - 400 - error: '802'.
WazuhAPI 2018-06-10 21:32:08: [::ffff:127.0.0.1] GET /cluster/status? - 400 - error: '802'.
WazuhAPI 2018-06-10 21:32:08: Internal Error
WazuhAPI 2018-06-10 21:32:08: Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:356:11)
    at ServerResponse.header (/var/ossec/api/node_modules/express/lib/response.js:767:10)
    at ServerResponse.header (/var/ossec/api/node_modules/express/lib/response.js:770:12)
    at cache (/var/ossec/api/node_modules/apicache/lib/apicache.js:156:15)
    at Layer.handle [as handle_request] (/var/ossec/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/ossec/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/ossec/api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/ossec/api/node_modules/express/lib/router/layer.js:95:5)
    at /var/ossec/api/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/ossec/api/node_modules/express/lib/router/index.js:335:12)
WazuhAPI 2018-06-10 21:32:08: Exiting...
```

This makes the API to force quit immediately, and we have to restart the service.

This doesn't happen if our app uses the 3.3.0 version to make requests to the API, so I think the problem is in the request headers.

Regards,
Juanjo

**Comment by jesuslinares** [comment]
Every request to the API should include the "app version":

```
# curl -XGET -u foo:bar "http://localhost:55000/version?pretty" -H "wazuh-app-version: 3.2.4"
{"error":"802","message":"Invalid 'wazuh-app-version' header. Expected version '3.3.x', and found '3.2.x'."}
```

When an API is added to the app, there are some requests without the header:

- GET /version
- GET /agents/000
- GET /cluster/status

I will check why the API is crashing.
