### ISSUE TITLE
RESTful API won't start

### ISSUE THREAD

**Issue by Tarliman** [wazuh/wazuh-api#108]
No changes were made to the server, as far as I can tell. We had a stable install of Kibana/Wazuh until two days ago. 

```[root@ossec etc]# systemctl status wazuh-api
● wazuh-api.service - Wazuh API daemon
   Loaded: loaded (/etc/systemd/system/wazuh-api.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-06-13 15:22:44 EDT; 5s ago
     Docs: http://wazuh-documentation.readthedocs.org/en/latest/ossec_api.html
  Process: 5460 ExecStart=/bin/node /var/ossec/api/app.js (code=exited, status=1/FAILURE)
 Main PID: 5460 (code=exited, status=1/FAILURE)

Jun 13 15:22:43 ossec.iconix.local systemd[1]: Started Wazuh API daemon.
Jun 13 15:22:43 ossec.iconix.local systemd[1]: Starting Wazuh API daemon...
Jun 13 15:22:44 ossec.iconix.local systemd[1]: wazuh-api.service: main process exited, code=exited, status=1/FAILURE
Jun 13 15:22:44 ossec.iconix.local systemd[1]: Unit wazuh-api.service entered failed state.
Jun 13 15:22:44 ossec.iconix.local systemd[1]: wazuh-api.service failed.
```

From api.log:

```WazuhAPI 2018-06-13 12:38:14: Internal Error: uncaughtException
WazuhAPI 2018-06-13 12:38:14: Error: listen EACCES foo
    at Object.exports._errnoException (util.js:1020:11)
    at exports._exceptionWithHostPort (util.js:1043:20)
    at Server._listen2 (net.js:1258:19)
    at listen (net.js:1307:10)
    at Server.listen (net.js:1396:5)
    at Object.<anonymous> (/var/ossec/api/app.js:225:41)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
WazuhAPI 2018-06-13 12:38:14: Exiting...
```

Various other log entries:

```2018/06/12 08:21:11 wazuh-modulesd:ciscat: INFO: Module disabled. Exiting...
2018/06/12 08:21:11 wazuh-modulesd:database: INFO: Module started.
2018/06/12 08:21:11 ossec-execd: INFO: Started (pid: 880).
2018/06/12 08:21:14 wazuh-modulesd: ERROR: (1210): Queue '/var/ossec/queue/ossec/queue' not accessible: 'Connection refused'.
2018/06/12 08:21:18 ossec-maild: INFO: Started (pid: 1473).
2018/06/12 08:21:18 ossec-maild: INFO: Getting alerts in log format.
```

```Jun 12 08:12:46 ossec kibana: {"type":"error","@timestamp":"2018-06-12T12:12:46Z","tags":[],"pid":26026,"level":"error","error":{"
message":"[search_phase_execution_exception] all shards failed","name":"Error","stack":"[search_phase_execution_exception] all sha
rds failed :: {\"path\":\"/.wazuh/wazuh-configuration/_search\",\"query\":{\"size\":100},\"statusCode\":503,\"response\":\"{\\\"er
ror\\\":{\\\"root_cause\\\":[],\\\"type\\\":\\\"search_phase_execution_exception\\\",\\\"reason\\\":\\\"all shards failed\\\",\\\"
phase\\\":\\\"query\\\",\\\"grouped\\\":true,\\\"failed_shards\\\":[]},\\\"status\\\":503}\"}\n    at respond (/usr/share/kibana/n
ode_modules/elasticsearch/src/lib/transport.js:295:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/s
rc/lib/transport.js:254:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http
.js:159:7)\n    at IncomingMessage.bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:729:21)\
n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:1
2)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_
tick.js:128:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":""
,"query":{},"pathname":"/api/wazuh-api/apiEntries","path":"/api/wazuh-api/apiEntries","href":"/api/wazuh-api/apiEntries"},"message
":"[search_phase_execution_exception] all shards failed"}
```

```Jun 13 12:50:00 ossec kibana: {"type":"log","@timestamp":"2018-06-13T16:50:00Z","tags":["\u001b[34mwazuh\u001b[39m","monitoring","error"],"pid":761,"message":"connect ECONNREFUSED 127.0.0.1:55000"}
```

I've run the usual port checks, firewall checks, and so forth, and am at a loss as to why the API cannot connect to localhost on port 55000. I've gone so far as to restart the server, and validate the kibana, ossec, elasticsearch, and logstash startups. Is there maybe another process that listens on that port that isn't running?

**Comment by jesuslinares** [comment]
Hi @Tarliman ,

Do you have another service running on port 55000 TCP?. Please, check the ports with `netstat -tunap | grep 55000` or similar.

Also, check the file `/var/ossec/logs/api.log` and run the API in foreground `node /var/ossec/api/app.js -f`.

Thanks,
Jesus Linares.

**Comment by Lifka** [comment]
Hi @Tarliman,

the error is `EACCES` when `app.js` tries to start listening. Seems the port `55000` is used by another process or you don't have permission. Make sure there are no other service trying to use that port.

Maybe you can try to set another port to the API to rule out a problem with that particular port. To do that modify the following line in `/var/ossec/api/configuration/config.js`:

https://github.com/wazuh/wazuh-api/blob/03cccb38cab6acebd5feeec91b1db18a5879757a/configuration/config.js#L11

And try again:

`node /var/ossec/api/app.js -f`

Best regards,
Javi.

**Comment by Tarliman** [comment]
Not sure where that file is. 

```
[root@ossec /]# find . -name config.js
./var/ossec/api/configuration/config.js
./var/ossec/api/node_modules/winston/lib/winston/config.js
./usr/lib/node_modules/npm/lib/config.js
./usr/share/kibana/node/lib/node_modules/npm/lib/config.js
./usr/share/kibana/node_modules/babel-core/lib/transformation/file/options/config.js
./usr/share/kibana/node_modules/babel-core/node_modules/babel-core/lib/transformation/file/options/config.js
./usr/share/kibana/node_modules/babel-register/node_modules/babel-core/lib/transformation/file/options/config.js
./usr/share/kibana/node_modules/core-js/build/config.js
./usr/share/kibana/node_modules/fbjs/node_modules/core-js/build/config.js
./usr/share/kibana/node_modules/react-color/.storybook/config.js
./usr/share/kibana/node_modules/svgo/lib/svgo/config.js
./usr/share/kibana/node_modules/vega-lite/build/src/compile/axis/config.js
./usr/share/kibana/node_modules/vega-lite/build/src/config.js
./usr/share/kibana/node_modules/vega-parser/src/config.js
./usr/share/kibana/src/core_plugins/metrics/public/components/vis_types/table/config.js
./usr/share/kibana/src/core_plugins/metrics/public/components/vis_types/timeseries/config.js
./usr/share/kibana/src/server/config/config.js
./usr/share/kibana/src/ui/public/config/config.js
```

I don't see a config.port variable being set to a numeric value in the config.js in /api/configuration. It looks like that variable is being used to hold the userID text string "foo". Should this be set to a numeric value?

```
[root@ossec /]# more ./var/ossec/api/configuration/config.js

var config = {};

// Basic configuration

// Path
config.ossec_path = "/var/ossec";
// The host to bind the API to.
config.host = "0.0.0.0";
// TCP Port used by the API.
config.port = "foo";
// Use HTTP protocol over TLS/SSL. Values: yes, no.
config.https = "no";
// Use HTTP authentication. Values: yes, no.
config.basic_auth = "yes";
//In case the API run behind a proxy server, turn to "yes" this feature. Values: yes, no.
config.BehindProxyServer = "no";
```

**Comment by Lifka** [comment]
That is the problem, in fact it appears in your log:

```
WazuhAPI 2018-06-14 09:24:28: Error: listen EACCES foo
```

You have to set the API port in `config.port`. It must be a numeric value in quotation marks. Like this:

https://github.com/wazuh/wazuh-api/blob/03cccb38cab6acebd5feeec91b1db18a5879757a/configuration/config.js#L11

Please let us know if this solves this issue.

**Comment by Tarliman** [comment]
It did, sort of. Setting the value to 54000 allowed me to bring up the API. I then had to edit the API configuration in the Wazuh plugin in Kibana from the web interface. At that point, I started getting version mismatch errors, where the header specification expected 3.3.x but found 3.2.x. I ran an update, and now Wazuh isn't on the Kibana sidebar menu...

**Comment by Tarliman** [comment]
I tried reinstalling the wazuh plugin. That didn't work.

```
[root@ossec ~]# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://packages.wazuh.com/wazuhapp/wazuhapp.zip
Attempting to transfer from https://artifacts.elastic.co/downloads/kibana-plugins/https://packages.wazuh.com/wazuhapp/wazuhapp.zip/https://packages.wazuh.com/wazuhapp/wazuhapp.zip-6.3.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```

**Comment by jesusgn90** [comment]
Hi @Tarliman I'm going to give you some light in your problem with Kibana.

First step of any attempt of reinstalling the Wazuh App you must to stop Kibana:

```
# systemctl stop kibana
```

Once Kibana is stopped you need to remove currently installed Wazuh App:

```
# /usr/share/kibana/bin/kibana-plugin remove wazuh
```

Now check your Kibana version:

```
# cat /usr/share/kibana/package.json | grep version
  "version": "6.2.4",
```
Note down your Kibana version, in example 6.2.4 and go to https://github.com/wazuh/wazuh-kibana-app#installation in order to check your compatible Wazuh App version.  Assuming your Kibana version is 6.2.4 and you have Wazuh 3.3.0 installed your installing command should be:

```
# /usr/share/kibana/bin/kibana-plugin install https://packages.wazuh.com/wazuhapp/wazuhapp-3.3.0_6.2.4.zip
```

Generic link for the Wazuh App looks like this:

```
https://packages.wazuh.com/wazuhapp/wazuhapp-<wazuh-version>_<kibana-version>.zip
```

Installing the Wazuh App takes some minutes, be patient. Once done restart Kibana:

```
# systemctl restart kibana
```

Next step is to clean your browser cache, cookies, etc. or open a new incognito window in your browser.

Hope it helps,
Jesús

**Comment by Tarliman** [comment]
```
[root@ossec ~]# cat /usr/share/kibana/package.json | grep version
  "version": "6.3.0",
```

The Kibana version table only goes up to 6.2.4.

**Comment by JuanjiJG** [comment]
Hello @Tarliman,

We're working on adapting the Wazuh app for Kibana 6.3.0. In the meantime, you have to install Kibana 6.2.4 in order to use our app.

Our latest app is compatible with Kibana 6.2.4 and Wazuh 3.3.0. You can follow our [Elastic installation guide](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html).

Let us know if you have more questions or problems.

Regards,
Juanjo

**Comment by Tarliman** [comment]
OK. Downgraded KIbana to 6.2.4. Installed Wazuh 3.3.0_6.2.4. Rebooted the server to make sure I had a clean start. Got Wazuh up. Looks like we're going to have to rebuild our entire instance - lost our dashboard, none of the agents are connecting, etc.

**Comment by Tarliman** [comment]
Any suggestions for agents not connecting after Wazuh reinstall, how to recover our dashboard, etc.?

**Comment by jesuslinares** [comment]
Hi @Tarliman ,

The dashboards are stored in Elasticsearch, the index is .kibana.

Regarding the agents, check the file `/var/ossec/etc/client.keys` in your manager. It should contains all the keys. Also, review the ossec.log of the managers and agents.

**Comment by jesuslinares** [comment]
Hi @Tarliman, 

I will close this issue since there is no activity for more than a month.

Feel free to open it if you have more questions.

Thanks.

**Comment by lukelee1987** [comment]
Hi all, sorry I have question to ask. Isn't it this "App.js" is part of the install_daemon.sh which will be called when we run systemctl wazuh-api start/restart ? why do we still need  to run this "node /var/ossec/api/app.js" manually ?? Is it a bug to report ?

**Comment by symbol-c** [comment]
hello @jesuslinares 
i am currently dealing with a similar issue
i am unable to start the wazuh api 
i get this when i try to start it
```
● wazuh-api.service - Wazuh API daemon
   Loaded: loaded (/etc/systemd/system/wazuh-api.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2020-07-20 09:57:01 WAT; 42min ago
     Docs: https://documentation.wazuh.com/current/user-manual/api/index.html
  Process: 5448 ExecStop=/bin/kill -HUP $MAINPID (code=exited, status=0/SUCCESS)
  Process: 5431 ExecStart=/usr/bin/nodejs /var/ossec/api/app.js (code=exited, status=1/FAILURE)
 Main PID: 5431 (code=exited, status=1/FAILURE)
   CGroup: /system.slice/wazuh-api.service

Jul 20 09:56:58 -Wazuh systemd[1]: Started Wazuh API daemon.
Jul 20 09:57:00 I-Wazuh systemd[1]: wazuh-api.service: Main process exited, code=exited, status=1/FAILURE
Jul 20 09:57:01 I-Wazuh systemd[1]: wazuh-api.service: Unit entered failed state.
Jul 20 09:57:01 I-Wazuh systemd[1]: wazuh-api.service: Failed with result 'exit-code

and when i check the logs i see this 
```
WazuhAPI 2020-07-20 11:00:07 : Internal Error: uncaughtException
WazuhAPI 2020-07-20 11:00:07 : Error: getaddrinfo ENOTFOUND locahost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
WazuhAPI 2020-07-20 11:00:07 : Exiting...

i have checked the etc/hosts/ file and it looks okay
Please can you help 

```
```'.
