### ISSUE TITLE
Error installing API Ubuntu 15.04

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-api#197]
Hello team

  I've tried to install and run Wazuh API in Ubuntu 15.04 successfully. After install it, the service doesn't start so I executed this: 

```
root@mytestbox9:/home/vagrant# node /var/ossec/api/app.js
Could not configure NodeJS to avoid unsecure SSL/TLS protocols: TypeError: Cannot read property 'SSL_OP_NO_SSLv3' of undefined
/var/ossec/api/helpers/request_templates.js:26
exports.single_field_array_request = function(entrypoint_name, req, res, apicacheGroup, param_cheks={}, query_cheks={}) {
                                                                                                   ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/var/ossec/api/controllers/index.js:16:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

```
I have used the dev repository, version 3.7.0. No upgrade. Node version: 5.10. 
Please, let me know if you need further details. 
Best regards, 

Alberto R.

**Comment by mgmacias95** [comment]
Done in https://github.com/wazuh/wazuh-api/pull/209
