### ISSUE TITLE
Error when changing API password/user

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-api#203]
Hi team,

I was trying to change the user and password of my API when I got the following error:

```shellsession
# cd /var/ossec/api/configuration/auth
# node htpasswd -c user marta -b marta
module.js:478
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/ossec/api/configuration/auth/htpasswd:3:16)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
```

Comparing with another API where I was actually able to change the API password, I noticed the following difference:
* Working API:
    ```shellsession
    # ls -l
    total 4
    lrwxrwxrwx. 1 root root 49 Oct  5 08:51 htpasswd -> /var/ossec/api/node_modules/htpasswd/bin/htpasswd
    -rw-rw----. 1 root root 44 Oct 15 10:15 user
    ```
* Non working API:
    ``` shellsession
    # ls -l
    total 8
    -rwxr-x---. 1 root root 123 Nov 10  2016 htpasswd
    -rw-rw----. 1 root root  42 Sep 20 17:47 user
    ```

The bug is fixed doing the link:
```shellsession
# rm htpasswd
# ln -s ../../node_modules/htpasswd/bin/htpasswd htpasswd
# node htpasswd -c user marta -b marta
Adding password for user marta.
```

Further research must be done to determine why the link wasn't created. It was an updated API.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Fixed in https://github.com/wazuh/wazuh-api/pull/205
