### ISSUE TITLE
API doesn't work under a custom directory

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-api#250]
Hello team,

I have a wazuh installation under `/opt/ossec` directory:
```shellsession
# cat /etc/ossec-init.conf
DIRECTORY="/opt/ossec"
NAME="Wazuh"
VERSION="v3.7.2"
REVISION="3726"
DATE="Mon Dec 10 15:47:52 UTC 2018"
TYPE="server"
```

All API calls return the same error:
```javascript
# curl -u foo:bar "localhost:55000/agents?pretty"
{
   "error": 3006,
   "message": "Error reading cluster configuration: Error getting configuration: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'"
}
```

After some research I found the error traceback:
```python
Traceback (most recent call last):
  File "/opt/ossec/api/models/wazuh-api.py", line 25, in <module>
    from wazuh.cluster.dapi import dapi
  File "/opt/ossec/framework/wazuh/cluster/dapi/dapi.py", line 6, in <module>
    import wazuh.cluster.dapi.requests_list as rq
  File "/opt/ossec/framework/wazuh/cluster/dapi/requests_list.py", line 17, in <module>
    import wazuh.cluster.control as cluster_control
  File "/opt/ossec/framework/wazuh/cluster/control.py", line 9, in <module>
    from wazuh.cluster.internal_socket import execute
  File "/opt/ossec/framework/wazuh/cluster/internal_socket.py", line 6, in <module>
    from wazuh.cluster import communication
  File "/opt/ossec/framework/wazuh/cluster/communication.py", line 37, in <module>
    if check_cluster_status():
  File "/opt/ossec/framework/wazuh/cluster/cluster.py", line 161, in check_cluster_status
    return read_config()['disabled'] != 'yes'
  File "/opt/ossec/framework/wazuh/cluster/cluster.py", line 129, in read_config
    raise WazuhException(3006, e.message)
wazuh.exception.WazuhException: Error 3006 - Error reading cluster configuration: Error getting configuration: [Errno 2] No such file or directory: '/var/ossec/etc/ossec.conf'
```

The `read_config` function is being called when importing the distributed API. Since the custom path (`/opt/ossec`) is set in the main function, the `read_function` is being called using the default one: `/var/ossec`.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Fixed in https://github.com/wazuh/wazuh-api/pull/266
