### ISSUE TITLE
Cannot find module '/var/ossec/api/app.js'

### ISSUE THREAD

**Issue by ictinc** [wazuh/wazuh-api#281]
I'm currently following the manual at securing the API:
https://documentation.wazuh.com/current/installation-guide/optional-configurations/securing-api.html

In the first step it says:
`cd /var/ossec/api/configuration/auth`
This directory does not exist while the Wazuh-API service is installed.
After creating the directory and htpasswd file I am able run:
`node htpasswd -c user myUserName`
However no password is asked.

After trying to restart the wazuh-api I receive the following error:
```
Jan 19 00:41:09 siem nodejs[28090]: module.js:550
Jan 19 00:41:09 siem nodejs[28090]:     throw err;
Jan 19 00:41:09 siem nodejs[28090]:     ^
Jan 19 00:41:09 siem nodejs[28090]: Error: Cannot find module '/var/ossec/api/app.js'
Jan 19 00:41:09 siem nodejs[28090]:     at Function.Module._resolveFilename (module.js:548:15)
Jan 19 00:41:09 siem nodejs[28090]:     at Function.Module._load (module.js:475:25)
Jan 19 00:41:09 siem nodejs[28090]:     at Function.Module.runMain (module.js:694:10)
Jan 19 00:41:09 siem nodejs[28090]:     at startup (bootstrap_node.js:204:16)
Jan 19 00:41:09 siem nodejs[28090]:     at bootstrap_node.js:625:3
Jan 19 00:41:09 siem systemd[1]: wazuh-api.service: Main process exited, code=exited, status=1/FAILURE
Jan 19 00:41:09 siem systemd[1]: wazuh-api.service: Failed with result 'exit-code'.
Jan 19 00:42:04 siem systemd[1]: wazuh-manager.service: Failed to load environment files: No such file or directory
Jan 19 00:42:04 siem systemd[1]: wazuh-manager.service: Failed to run 'start' task: No such file or directory
Jan 19 00:42:04 siem systemd[1]: wazuh-manager.service: Failed with result 'resources'.
Jan 19 00:42:04 siem systemd[1]: Failed to start Wazuh manager.
```
This is where I'm stuck.
I'm running Ubuntu 18.04 with current updates.

Kind regards.

**Comment by mgmacias95** [comment]
Hello @ictinc,

Sorry for the late response. This is the directory structure created when the API is installed:
```shellsession
# ls -l /var/ossec/api/
total 44
-rwxr-x---   1 root ossec 8247 Jan 30 15:27 app.js
drwxr-x---   4 root ossec 4096 Feb 13 09:19 configuration
drwxr-x---   2 root ossec 4096 Feb 13 09:19 controllers
drwxr-x---   2 root ossec 4096 Feb 13 09:19 examples
drwxr-x---   2 root ossec 4096 Feb 13 09:19 helpers
drwxr-x---   2 root ossec 4096 Feb 13 09:19 models
drwxr-x--- 100 root ossec 4096 Feb 13 09:19 node_modules
-rw-r-----   1 root ossec  792 Jan 30 15:27 package.json
drwxr-x---   2 root root  4096 Feb 13 09:19 scripts
```
The binary `htpasswd` is a link to one of the NPM dependencies the API installs:
```shellsession
# ls -l /var/ossec/api/configuration/auth/
total 4
lrwxrwxrwx 1 root root 49 Feb 13 09:19 htpasswd -> /var/ossec/api/node_modules/htpasswd/bin/htpasswd
-rw-rw---- 1 root root 42 Jan 30 15:27 user
```
Can you please share the output of the commands above? I need to verify your installation is correct before giving further assistance.

Best regards,
Marta

**Comment by crd1985** [comment]
Closing the issue due to inactivity.
