### ISSUE TITLE
Internal API error when using the API call GET/manager/files without specifying a file

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-api#342]
Hello team,

Using the `GET/manager/files` API call without specifying any argument returns an unhandled exception:
```shellsession
root@master:/home/vagrant# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/manager/files?path=etc/rules/local_rules.xml&pretty"
{
   "error": 0,
   "data": "<!-- Local rules -->\n\n<!-- Modify it at your will. -->\n<!-- Copyright (C) 2015-2019, Wazuh Inc. -->\n\n<!-- Example -->\n<group name=\"local,syslog,sshd,\">\n\n  <!--\n  Dec 10 01:02:02 host sshd[1234]: Failed none for root from 1.1.1.1 port 1066 ssh2\n
 -->\n  <rule id=\"100001\" level=\"5\">\n    <if_sid>5716</if_sid>\n    <srcip>1.1.1.1</srcip>\n    <description>sshd: authentication failed from IP 1.1.1.1.</description>\n    <group>authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>\n  </rule>\n\n</group>\n"
}
root@master:/home/vagrant# curl -u foo:bar -k -X GET "http://127.0.0.1:55000/manager/files?pretty"
{
   "error": 3,
   "message": "Internal error"
}
root@master:/home/vagrant# tail -n30 /var/ossec/logs/api.log
WazuhAPI 2019-03-07 15:54:11 : Listening on: http://:::55000
WazuhAPI 2019-03-07 15:55:00 foo: [::ffff:127.0.0.1] GET /cluster/node02/files?path=etc/rules/local_rules.xml&pretty - 200 - error: '3022'.
WazuhAPI 2019-03-07 15:55:08 foo: [::ffff:127.0.0.1] GET /manager/files?path=etc/rules/local_rules.xml&pretty - 200 - error: '0'.
WazuhAPI 2019-03-07 15:55:17 foo: Internal Error
WazuhAPI 2019-03-07 15:55:17 foo: TypeError: Cannot read property 'includes' of undefined
    at Object.exports.check_path (/var/ossec/api/helpers/filters.js:61:14)
    at /var/ossec/api/controllers/manager.js:305:17
    at Layer.handle [as handle_request] (/var/ossec/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/ossec/api/node_modules/express/lib/router/route.js:137:13)
    at buildCacheObj (/var/ossec/api/node_modules/apicache/lib/apicache.js:241:9)
    at cache (/var/ossec/api/node_modules/apicache/lib/apicache.js:188:9)
    at Layer.handle [as handle_request] (/var/ossec/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/ossec/api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/ossec/api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/ossec/api/node_modules/express/lib/router/layer.js:95:5)
WazuhAPI 2019-03-07 15:55:17 foo: Exiting...
WazuhAPI 2019-03-07 15:55:17 foo: [::ffff:127.0.0.1] GET /manager/files?pretty - 500 - error: '3'.
root@master:/home/vagrant# systemctl status wazuh-api
● wazuh-api.service - Wazuh API daemon
   Loaded: loaded (/etc/systemd/system/wazuh-api.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-03-07 15:54:10 UTC; 2min 12s ago
     Docs: https://documentation.wazuh.com/current/user-manual/api/index.html
 Main PID: 7856 (nodejs)
    Tasks: 10 (limit: 547)
   CGroup: /system.slice/wazuh-api.service
           └─7856 /usr/bin/nodejs /var/ossec/api/app.js

Mar 07 15:54:10 master systemd[1]: Started Wazuh API daemon.
```

Best regards,
Marta

**Comment by crd1985** [comment]
We should check also the POST and DELETE calls. I see that this case is not included in mocha tests, so it has not been detected before, please check other mocha tests in order to anticipate similar errors. Thanks!
