### ISSUE TITLE
api fails when basic_auth is disabled

### ISSUE THREAD

**Issue by rascalking** [wazuh/wazuh-api#8]
Here's the relevant output from `journalctl -u wazuh-api`:

```Apr 26 16:21:06 barricades systemd[1]: Started Wazuh API daemon.
Apr 26 16:21:06 barricades nodejs[14466]: /var/ossec/api/app.js:113
Apr 26 16:21:06 barricades nodejs[14466]: auth_secure.on('fail', (result, req) => {
Apr 26 16:21:06 barricades nodejs[14466]: ^
Apr 26 16:21:06 barricades nodejs[14466]: TypeError: Cannot read property 'on' of undefined
Apr 26 16:21:06 barricades nodejs[14466]: at Object.<anonymous> (/var/ossec/api/app.js:113:12)
Apr 26 16:21:06 barricades nodejs[14466]: at Module._compile (module.js:570:32)
Apr 26 16:21:06 barricades nodejs[14466]: at Object.Module._extensions..js (module.js:579:10)
Apr 26 16:21:06 barricades nodejs[14466]: at Module.load (module.js:487:32)
Apr 26 16:21:06 barricades nodejs[14466]: at tryModuleLoad (module.js:446:12)
Apr 26 16:21:06 barricades nodejs[14466]: at Function.Module._load (module.js:438:3)
Apr 26 16:21:06 barricades nodejs[14466]: at Module.runMain (module.js:604:10)
Apr 26 16:21:06 barricades nodejs[14466]: at run (bootstrap_node.js:393:7)
Apr 26 16:21:06 barricades nodejs[14466]: at startup (bootstrap_node.js:150:9)
Apr 26 16:21:06 barricades nodejs[14466]: at bootstrap_node.js:508:3
Apr 26 16:21:06 barricades systemd[1]: wazuh-api.service: main process exited, code=exited, status=1/FAILURE
```

PR incoming.

**Comment by jesuslinares** [comment]
Nice catch. Pull request accepted.

Thanks for your feedback.
